import { platformCopy, chartLabel } from './platform-copy.js';
import React, { useState } from 'react';
import { DataComponent, EvidenceChart, Dropdown, RichNarrative } from '../../data-app-public.jsx';
import { ListenLinks } from './ListenLinks.jsx';
import { pct, archiveDates, weekKey } from './weekly-model.js';
import { periodLabel } from './music-model.js';
const nf = n => new Intl.NumberFormat('zh-TW').format(n);
function External({href,children}) { return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>; }
export function WeeklyReview({all=[],issues,onArchive,initialIssue}) {
  const [search,setSearch]=useState('');
  const [month,setMonth]=useState('全部月份');
  const [issueId,setIssueId]=useState(initialIssue||issues[0]?.id);
  const list=issues.filter(i=>(month==='全部月份'||i.publishedAt.startsWith(month))&&`${platformCopy(i.title)} ${i.tags.join(' ')} ${i.mandarinText} ${i.globalText} ${i.candidates.map(r=>r.title+' '+r.artist).join(' ')}`.toLowerCase().includes(search.trim().toLowerCase()));
  const active=list.find(i=>i.id===issueId)||list[0];
  const index=list.indexOf(active), m=active?.metrics;
  const choose=id=>{setIssueId(id);window.scrollTo(0,0);window.history.replaceState(null,'',`#weekly/${id}`);};
  return <div className="ms-library">
    <div className="ms-library-head"><div><span className="ms-kicker">WEEKLY / OBSERVATIONS</span><h2>本週音樂觀察</h2><p>每週一篇，把數據留下，也把當時的判斷留下。</p></div><button className="ms-outline" onClick={()=>onArchive()}>回顧歷史榜單 ↗</button></div>
    <div className="ms-library-tools"><label className="ms-search"><span aria-hidden="true">⌕</span><input aria-label="搜尋觀察文章" placeholder="搜尋主題、歌手、歌曲…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Dropdown label="發布月份" value={month} choices={['全部月份',...new Set(issues.map(i=>i.publishedAt.slice(0,7)))]} onChange={setMonth}/><span className="ms-note" role="status">{list.length} 篇觀察</span></div>
    <div className="ms-library-grid"><aside className="ms-issue-list" aria-label="歷期觀察文章"><h3>觀察檔案</h3>{list.map((i,n)=><button key={i.id} className={active?.id===i.id?'is-active':''} onClick={()=>choose(i.id)} aria-current={active?.id===i.id?'page':undefined}><small>{i.id} <b>{i.id===issues[0]?.id?'最新一期':''}</b></small><strong>{platformCopy(i.title)}</strong><span>{i.publishedAt} 發布 · 華語 / 全球</span></button>)}<p>已封存 {issues.length} 篇。舊文章保留發表時的數據與結論；沒有發布過的週次不補造文章。</p></aside>
    {!active?<div className="ms-empty"><h3>沒有符合條件的文章</h3><p>試試其他關鍵字，或清除月份篩選。</p><button className="ms-outline" onClick={()=>{setSearch('');setMonth('全部月份');}}>清除篩選</button></div>:<article className="ms-weekly-article" key={active.id}>
      <header><span className="ms-kicker">{active.id} · {active.weekStart} — {active.weekEnd}</span><h2>{platformCopy(active.title)}</h2><p className="ms-article-deck">{platformCopy(active.summary)}</p><div className="ms-article-meta"><span>發布 {active.publishedAt}</span><span>封存版本 · 描述性分析</span><span>約 6 分鐘閱讀</span></div></header>
      <nav className="ms-article-toc" aria-label="文章目錄">{[['coverage','資料期間'],['mandarin','華語觀察'],['world','全球觀察'],['cross','平台交集'],['watch','下週追蹤'],['method','研究方法']].map(([id,t])=><a key={id} href={`#issue-${id}`} onClick={e=>{e.preventDefault();document.getElementById(`issue-${id}`)?.scrollIntoView({behavior:'smooth',block:'start'});}}>{t}</a>)}</nav>
      <section id="issue-coverage" className="ms-article-section"><h3>先看這篇觀察的資料期間</h3><p className="ms-notice">發布週不等於統計週。華語觀察窗為 {m.kkStart} ～ {m.kkEnd}；YouTube 全球最新週榜截至 {m.ytEnd}。Spotify 是歌單更新快照，不能與週榜視為同一期間。</p>
      <details className="ms-method"><summary>各來源日期與完整證據</summary><DataComponent id={`weekly-coverage-${active.id}`} queryId="weekly" title="本期來源覆蓋" displayRows={active.coverage} sourceRows={[active]} variant="plain" kind="table"><div className="ms-weekly-coverage" data-reviewed-rows>{active.coverage.map(c=><div key={[c.platform,c.market,c.chart].join('|')}><strong>{c.platform}</strong><span>{chartLabel(c)} · {c.count} 首</span><span>{c.periodStart?`${c.periodStart} ～ `:''}{c.date}</span><External href={c.url}>原始榜單</External></div>)}</div></DataComponent></details></section>
      <DataComponent id={`weekly-article-${active.id}`} queryId="weekly" title="本期分析與解讀" sourceRows={[active]} displayRows={[{週次:active.id,華語觀察:active.mandarinText,全球觀察:active.globalText}]} variant="plain" kind="custom">
      <section id="issue-mandarin" className="ms-article-section"><span className="ms-kicker">01 / MANDARIN</span><h3>華語：先分辨作品集中與風格擴散</h3><RichNarrative id={`weekly-mandarin-${active.id}`} value={platformCopy(active.mandarinText)}/><div className="ms-article-callout"><b>怎麼解讀</b><p>{platformCopy(active.mandarinInterpretation)}</p></div>
      {active.artistSeats.length>0&&<EvidenceChart id={`weekly-seats-${active.id}`} queryId="weekly" title={`${m.kkLead} 在 KKBOX 華語 Top ${m.kkCount} 的每日席次`} rows={active.artistSeats} sourceRows={[active]} spec={{type:'bar',x:'日期',y:'榜單席次',stackable:false,valueDecimals:0}} height={250} variant="card"><p className="ms-note">每首歌占一席，分母為該日 Top {m.kkCount}；0 表示已取得的當日榜單沒有該歌手作品，未取得的日期不補零。</p></EvidenceChart>}</section>
      <section id="issue-world" className="ms-article-section"><span className="ms-kicker">02 / GLOBAL</span><h3>全球：總觀看與典型歌曲，可能走不同方向</h3><RichNarrative id={`weekly-world-${active.id}`} value={platformCopy(active.globalText)}/><div className="ms-evidence-pair" data-reviewed-rows><div><small>固定在榜群的總觀看變化</small><strong>{pct(m.cohortGrowth)}</strong><span>{m.cohortCount} 首可比歌曲 · 受大流量作品影響</span></div><div><small>同一群歌曲的逐首增幅中位數</small><strong>{pct(m.medianGrowth)}</strong><span>先逐首計算，再取中間值</span></div></div>
      {active.globalShares.length>0&&<EvidenceChart id={`weekly-concentration-${active.id}`} queryId="weekly" title="全球榜前 10 名占 Top 100 觀看量的比例" rows={active.globalShares} sourceRows={[active]} spec={{type:'bar',x:'日期',y:'Top 10 觀看占比 (%)',stackable:false,valueDecimals:1}} height={250} variant="card"><p className="ms-note">各週分別以自己的 Top 100 為分母。{active.globalShares.length===2&&`從 ${active.globalShares[0]['Top 10 觀看占比 (%)'].toFixed(1)}% 到 ${active.globalShares[1]['Top 10 觀看占比 (%)'].toFixed(1)}%，差 ${(active.globalShares[1]['Top 10 觀看占比 (%)']-active.globalShares[0]['Top 10 觀看占比 (%)']).toFixed(1)} 個百分點。`}</p></EvidenceChart>}<div className="ms-article-callout"><b>證據邊界</b><p>{platformCopy(active.globalInterpretation)}</p></div></section>
      <section id="issue-cross" className="ms-article-section"><span className="ms-kicker">03 / CROSS-PLATFORM</span><h3>Spotify × YouTube：熱度交集，保留差異</h3><p>各取全球前 50 名，本期可保守配對 {m.globalMatches} 首；Spotify 實際收錄 {m.spotifyCount} 首、YouTube {m.youtubeCount} 首。相同歌名與完整歌手名單才配對，譯名與版本差異可能漏配。兩份榜單日期不同，這是跨平台可見度的線索，尚不足以證明本週同步擴散。</p><div className="ms-weekly-matches" data-reviewed-rows>{active.matches.map(r=><div key={r.title+r.artist}><strong>{r.title}<small>{r.artist}</small></strong><span>Spotify 第 {r.spotifyRank} 名<small>{r.spotifyDate} 更新</small></span><span>YouTube 第 {r.youtubeRank} 名<small>週榜截至 {r.youtubeDate}</small></span></div>)}</div>{!active.matches.length&&<p>本期沒有可確認的交集；不等於兩個平台完全沒有相同歌曲。</p>}</section>
      <section id="issue-watch" className="ms-article-section"><span className="ms-kicker">04 / WATCH NEXT</span><h3>下一期要驗證的線索</h3><p>以下歌曲在 YouTube 全球榜出現不超過 4 週，且相鄰兩期觀看增加。依增幅選取最多 3 首；這是追蹤清單，並非「新人」或「即將爆紅」的認證。</p><div className="ms-watch-cards" data-reviewed-rows>{active.candidates.map(r=><div key={r.id}><small>在榜 {r.weeksOnChart} 週 · 第 {r.rank} 名</small><h4>{r.title}</h4><p>{r.artist}</p><strong>{pct(r.calculatedGrowth)}</strong><span>{nf(r.priorViews)} → {nf(r.views)} 次／週</span><ListenLinks row={r} all={all}/></div>)}</div>{!active.candidates.length&&<p>本期沒有符合條件且資料完整的候選。</p>}<RichNarrative id={`weekly-next-${active.id}`} value={platformCopy(active.nextWeek)}/></section>
      </DataComponent>
      <section id="issue-method" className="ms-article-section"><span className="ms-kicker">METHOD / REPRODUCIBLE</span><h3>方法、限制與參考依據</h3><p>這是一份可重算的描述性觀察。統計方法幫助我們避免誤讀，並不讓短期榜單具有預知流行的能力。</p><ol className="ms-method-list">{active.methods.map(s=><li key={s}>{platformCopy(s)}</li>)}</ol><p>抖音、QQ 音樂尚未接入，本期尚無這兩個平台的完整觀察。歌詞與曲風沒有足夠驗證資料，保留為待研究問題。</p><div className="ms-reference-links">{active.references.map(s=><External key={s.url} href={s.url}>{platformCopy(s.title)}</External>)}</div></section>
      <div className="ms-article-bottom"><button className="ms-outline" disabled={index>=list.length-1} onClick={()=>choose(list[index+1].id)}>← 上一期</button><button className="ms-outline" onClick={()=>onArchive(m.kkEnd, 'KKBOX')}>查看本期華語榜單</button><button className="ms-outline" disabled={index<=0} onClick={()=>choose(list[index-1].id)}>下一期 →</button></div>
    </article>}</div>
  </div>;
}
export function MusicArchive({all,issues,onRead,onExplore,initialDate,initialPlatform}) {
  const [month,setMonth]=useState('全部月份'),[platform,setPlatform]=useState(initialPlatform||'全部平台'),[search,setSearch]=useState(''),[selectedDate,setDate]=useState(initialDate||all.map(r=>r.date).sort().at(-1));
  const [limit,setLimit]=useState(30);
  const dates=archiveDates(all,month,platform);
  const active=dates.find(d=>d.date===selectedDate)||dates[0];
  const records=all.filter(r=>r.date===active?.date&&(platform==='全部平台'||r.platform===platform)&&`${r.title} ${r.artist}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>a.platform.localeCompare(b.platform)||a.market.localeCompare(b.market)||a.rank-b.rank);
  const related=issues.filter(i=>active&&i.id===weekKey(active.date));
  return <section className="ms-archive"><div className="ms-library-head"><div><span className="ms-kicker">ARCHIVE / TIMELINE</span><h2>歷史回顧</h2><p>選一個榜單日期，回看實際保存的歌曲與名次。</p></div><button className="ms-outline" onClick={()=>onRead()}>觀察文章檔案 ↗</button></div><div className="ms-library-tools"><Dropdown label="榜單月份" value={month} choices={['全部月份',...new Set(all.map(r=>r.date.slice(0,7)).sort().reverse())]} onChange={v=>{setMonth(v);setLimit(30);}}/><Dropdown label="歷史平台" value={platform} choices={['全部平台',...new Set(all.map(r=>r.platform))]} onChange={v=>{setPlatform(v);setLimit(30);}}/><label className="ms-search"><span aria-hidden="true">⌕</span><input aria-label="搜尋歷史歌曲" value={search} placeholder="搜尋當日歌曲、歌手…" onChange={e=>{setSearch(e.target.value);setLimit(30);}}/></label></div>
    <div className="ms-archive-dates" aria-label="已保存的榜單日期">{dates.map(d=><button key={d.date} aria-pressed={active?.date===d.date} onClick={()=>{setDate(d.date);setLimit(30);}}><strong>{d.date.slice(5).replace('-',' / ')}</strong><span>{d.count} 筆</span><small>{d.platforms.join(' · ')}</small></button>)}</div>
    <div className="ms-archive-header"><div><h3>{active?.date||'此範圍沒有資料'}</h3><p>{records.length} 筆符合篩選的紀錄。只顯示此日期的榜單；週榜日期是統計結束日。</p></div>{active&&<button className="ms-outline" onClick={()=>onExplore(active.date,platform)}>到榜單明細比較歌曲 ↗</button>}</div>
    <div className="ms-archive-related">{related.length?related.map(i=><button key={i.id} onClick={()=>onRead(i.id)}>閱讀此發布週的觀察 · {platformCopy(i.title)} ↗</button>):<span>這個日期所屬的週次尚未發布觀察文章；榜單資料仍可回顧。</span>}</div>
    <DataComponent id="historical-chart-records" queryId="tracks" title="所選日期的歷史紀錄" sourceRows={records} displayRows={records} kind="table" variant="card"><div className="ms-archive-records" data-reviewed-rows>{records.slice(0,limit).map(r=><div key={[r.date,r.platform,r.market,r.chart,r.id].join('|')}><b>第 {r.rank} 名</b><div><strong>{r.title}</strong><small>{r.artist}</small></div><div><span>{r.platform}</span><small>{periodLabel(r)}</small><small>{r.views!=null?`${nf(r.views)} 次／週`:chartLabel(r)}</small></div><div><ListenLinks row={r} all={all}/><External href={r.sourceUrl}>原榜</External></div></div>)}</div>{!records.length&&<p className="ms-note">沒有符合篩選的歷史紀錄。</p>}{records.length>limit&&<button className="ms-more" onClick={()=>setLimit(v=>v+30)}>再看 {Math.min(30,records.length-limit)} 筆 ↓</button>}</DataComponent>
  </section>;
}
